### ISSUE TITLE
preProcess not available

### ISSUE THREAD

**Issue by BSchilperoort** [tomchor/pymicra#4]
With the latest version installed, I attempted to use the pymicra.preProcess function, however this is not available. eddyCovariance also seems to be missing.
Perhaps some import issue? They are in the util.py file, but don't seem to be properly imported.

![image](https://user-images.githubusercontent.com/12114825/34984190-52a44f66-fab0-11e7-8829-1f8fcffb42e1.png)

Other functions (data import, spectra) do seem to work.

**Comment by BSchilperoort** [comment]
Figured out the issue by looking at your AGU poster :)
I was missing the 'micro' part, ie. pm.micro.preProcess

The tutorial I was looking at did not have this part (https://tomchor.github.io/pymicra/tutorial.html)

**Comment by tomchor** [comment]
I moved the website from gh-pages to readthedocs because of the better version management and I ended up not deleting the old site, which was outdated. Just deleted gh-pages now, so there should be no confusion.
