### ISSUE TITLE
preProcessing fails when there is no H2O data in the dataset

### ISSUE THREAD

**Issue by BSchilperoort** [tomchor/pymicra#5]
In a dataset without H2O data, the preprocessing step will fail, as it checks for an label which is not in the pandas dataframe.
Perhaps add a check, or option to skip the H2O related processing steps?

**Comment by tomchor** [comment]
Yes, that's probably a good way to go. I'll mark it as an enhancement.

**Comment by tomchor** [comment]
Done via pull pull request/merge
https://github.com/tomchor/pymicra/pull/6

**Comment by tomchor** [comment]
Just for the sake of completeness, I pushed a [fix](https://github.com/tomchor/pymicra/commit/b144a8826768c0fb7b6d564ea68be4dc8ee7813f) to a bug that happened when `skip_h2o` was True and when there was a solute.
